version: '3.8'

services:
  log-detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filebeat
    volumes:
      # 挂载宿主机日志目录（只读）
      - /var/log:/var/log/host:ro
      # 挂载输出目录
      - ./output:/app/output
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
